services:
  - type: web
    name: llm-quiz-agent
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: EMAIL
        sync: false
      - key: SECRET
        sync: false
      - key: AIPIPE_TOKEN
        sync: false
